#!/usr/bin/env python3

import numpy as np
import sys

M = 20000
N = 400

def toarray(filename, shape=None):
    return np.fromfile(filename, dtype=np.float64).reshape(shape)

def verify(filename):
    A = np.matrix(toarray(filename, (N,M)))
    return np.amax(np.abs(A*A.T - np.identity(N)))

def diff(filename1, filename2):
    return np.sqrt(np.mean(np.square(toarray(filename1) - toarray(filename2)) / toarray(filename2)))

argc = len(sys.argv)

if argc == 2:
    print('Max element of (A * A^T - I):', verify(sys.argv[1]))
elif argc == 3:
    print('Root mean square of relative errors:', diff(sys.argv[1], sys.argv[2]))
else:
    print('Usage:')
    print('\n[Verification]\n\tpython', sys.argv[0], '[filename]')
    print('\n[Diff]\n\tpython', sys.argv[0], '[filename1] [filename2]')
